### ISSUE TITLE
Change name to Parsero

### ISSUE THREAD

**Issue by appositum** [appositum/parsero#22]
po ai ce me fode ne meu parsero... kk

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/41040470/49491468-68cfae00-f83b-11e8-902a-6fe1c0e1aea1.png)

**Comment by sqdorte** [comment]
![image](https://user-images.githubusercontent.com/38764914/49492127-2f4c7200-f83e-11e8-8b81-56d8b15b52ae.png)

**Comment by appositum** [comment]
Solved #23
